from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArticleSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="GameClass",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("details", models.TextField()),
                ("tags", models.JSONField(blank=True, default=list)),
                ("hit_dice", models.CharField(blank=True, default="", max_length=50)),
                ("primary_ability", models.CharField(blank=True, default="", max_length=255)),
                ("saving_throws", models.CharField(blank=True, default="", max_length=255)),
                ("armor_proficiencies", models.CharField(blank=True, default="", max_length=255)),
                ("weapon_proficiencies", models.CharField(blank=True, default="", max_length=255)),
                ("tool_proficiencies", models.CharField(blank=True, default="", max_length=255)),
                ("skill_proficiencies", models.CharField(blank=True, default="", max_length=255)),
                ("starting_equipment", models.TextField(blank=True, default="")),
                ("spellcasting_ability", models.CharField(blank=True, default="", max_length=255)),
                ("class_features", models.JSONField(blank=True, default=dict)),
                ("source", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="Beast",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("details", models.TextField()),
                ("tags", models.JSONField(blank=True, default=list)),
                ("type", models.CharField(blank=True, default="", max_length=255)),
                ("size", models.CharField(blank=True, default="", max_length=255)),
                ("alignment", models.CharField(blank=True, default="", max_length=255)),
                ("armor_class", models.CharField(blank=True, default="", max_length=255)),
                ("hit_points", models.CharField(blank=True, default="", max_length=255)),
                ("speed", models.CharField(blank=True, default="", max_length=255)),
                ("challenge_rating", models.CharField(blank=True, default="", max_length=255)),
                ("source", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("details", models.TextField()),
                ("tags", models.JSONField(blank=True, default=list)),
                ("capital", models.CharField(blank=True, default="", max_length=255)),
                ("government", models.CharField(blank=True, default="", max_length=255)),
                ("population", models.CharField(blank=True, default="", max_length=255)),
                ("major_cities", models.CharField(blank=True, default="", max_length=255)),
                ("climate", models.CharField(blank=True, default="", max_length=255)),
                ("source", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("details", models.TextField()),
                ("tags", models.JSONField(blank=True, default=list)),
                ("weight", models.CharField(blank=True, default="", max_length=50)),
                ("price", models.CharField(blank=True, default="", max_length=50)),
                ("size", models.CharField(blank=True, default="", max_length=50)),
                ("hit_points", models.CharField(blank=True, default="", max_length=50)),
                ("urbanization_level", models.PositiveIntegerField(default=1)),
                ("predominant_material", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="God",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("details", models.TextField()),
                ("tags", models.JSONField(blank=True, default=list)),
                ("alignment", models.CharField(blank=True, default="", max_length=255)),
                ("domains", models.CharField(blank=True, default="", max_length=255)),
                ("symbol", models.CharField(blank=True, default="", max_length=255)),
                ("worshippers", models.CharField(blank=True, default="", max_length=255)),
                ("source", models.CharField(blank=True, default="", max_length=255)),
                ("churches", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("details", models.TextField()),
                ("tags", models.JSONField(blank=True, default=list)),
                ("tier", models.CharField(choices=[("Major", "Major"), ("Minor", "Minor")], default="Minor", max_length=10)),
                ("rarity", models.CharField(blank=True, default="", max_length=255)),
                ("class_requirement", models.CharField(blank=True, default="", max_length=255)),
                ("item_type", models.CharField(max_length=255)),
                ("source", models.CharField(blank=True, default="", max_length=255)),
                ("price", models.CharField(blank=True, default="", max_length=50)),
                ("weight", models.CharField(blank=True, default="", max_length=50)),
                ("attunement", models.BooleanField(default=False)),
                ("consumable", models.BooleanField(default=False)),
                ("requirements", models.TextField(blank=True, default="")),
                ("urbanization_level", models.PositiveIntegerField(default=1)),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("details", models.TextField()),
                ("tags", models.JSONField(blank=True, default=list)),
                ("creature_type", models.CharField(blank=True, default="", max_length=255)),
                ("size", models.CharField(blank=True, default="", max_length=255)),
                ("speed", models.CharField(blank=True, default="", max_length=255)),
                ("starting_traits", models.TextField(blank=True, default="")),
                ("source", models.CharField(blank=True, default="", max_length=255)),
                ("ability_score_increase", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="Trait",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("details", models.TextField()),
                ("tags", models.JSONField(blank=True, default=list)),
                ("prerequisites", models.TextField(blank=True, default="")),
                ("benefits", models.TextField(blank=True, default="")),
                ("source", models.CharField(blank=True, default="", max_length=255)),
                (
                    "trait_type",
                    models.CharField(
                        choices=[
                            ("ancestry", "Ancestry"),
                            ("class", "Class"),
                            ("background", "Background"),
                            ("regional", "Regional"),
                            ("feat", "Feat"),
                            ("other", "Other"),
                        ],
                        default="ancestry",
                        max_length=32,
                    ),
                ),
                ("alternative_ability_score", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="Subclass",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("features", models.JSONField(blank=True, default=dict)),
                (
                    "game_class",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subclasses", to="api.gameclass"),
                ),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("details", models.TextField()),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="articles", to="api.articlesection"
                    ),
                ),
            ],
            options={"ordering": ("name",)},
        ),
    ]
